CRITICAL - 2022-07-21 01:57:36 --> syntax error, unexpected '$routes' (T_VARIABLE)
#0 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(364): CodeIgniter\CodeIgniter->tryToRouteIt(NULL)
#1 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#3 {main}
CRITICAL - 2022-07-21 02:01:36 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:12:34 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:13:29 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:13:40 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:14:12 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:23:46 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:23:55 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:30:00 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:30:54 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:35:03 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:38:27 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:50:53 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:57:35 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 02:57:38 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 03:01:38 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 03:02:14 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(24): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 03:08:19 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 03:09:41 --> syntax error, unexpected '$db' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
#0 /php_app/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('/php_app/app/Co...')
#1 /php_app/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Database')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Database')
#3 /php_app/vendor/codeigniter4/framework/system/Debug/Toolbar/Collectors/Database.php(100): spl_autoload_call('Config\\Database')
#4 /php_app/vendor/codeigniter4/framework/system/Debug/Toolbar.php(96): CodeIgniter\Debug\Toolbar\Collectors\Database->__construct()
#5 /php_app/vendor/codeigniter4/framework/system/Config/Services.php(856): CodeIgniter\Debug\Toolbar->__construct(Object(Config\Toolbar))
#6 /php_app/vendor/codeigniter4/framework/system/Config/BaseService.php(123): CodeIgniter\Config\Services::toolbar(Object(Config\Toolbar), false)
#7 /php_app/vendor/codeigniter4/framework/system/Config/Services.php(848): CodeIgniter\Config\BaseService::getSharedInstance('toolbar', NULL)
#8 /php_app/app/Config/Events.php(50): CodeIgniter\Config\Services::toolbar()
#9 [internal function]: CodeIgniter\Events\Events::Config\{closure}()
#10 /php_app/vendor/codeigniter4/framework/system/Events/Events.php(188): call_user_func(Object(Closure))
#11 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(293): CodeIgniter\Events\Events::trigger('pre_system')
#12 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-07-21 03:20:25 --> syntax error, unexpected '$db' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
#0 /php_app/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('/php_app/app/Co...')
#1 /php_app/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Database')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Database')
#3 /php_app/vendor/codeigniter4/framework/system/Debug/Toolbar/Collectors/Database.php(100): spl_autoload_call('Config\\Database')
#4 /php_app/vendor/codeigniter4/framework/system/Debug/Toolbar.php(96): CodeIgniter\Debug\Toolbar\Collectors\Database->__construct()
#5 /php_app/vendor/codeigniter4/framework/system/Config/Services.php(856): CodeIgniter\Debug\Toolbar->__construct(Object(Config\Toolbar))
#6 /php_app/vendor/codeigniter4/framework/system/Config/BaseService.php(123): CodeIgniter\Config\Services::toolbar(Object(Config\Toolbar), false)
#7 /php_app/vendor/codeigniter4/framework/system/Config/Services.php(848): CodeIgniter\Config\BaseService::getSharedInstance('toolbar', NULL)
#8 /php_app/app/Config/Events.php(50): CodeIgniter\Config\Services::toolbar()
#9 [internal function]: CodeIgniter\Events\Events::Config\{closure}()
#10 /php_app/vendor/codeigniter4/framework/system/Events/Events.php(188): call_user_func(Object(Closure))
#11 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(293): CodeIgniter\Events\Events::trigger('pre_system')
#12 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-07-21 03:26:18 --> syntax error, unexpected '$custom' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
#0 /php_app/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('/php_app/app/Co...')
#1 /php_app/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Database')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Database')
#3 /php_app/vendor/codeigniter4/framework/system/Debug/Toolbar/Collectors/Database.php(100): spl_autoload_call('Config\\Database')
#4 /php_app/vendor/codeigniter4/framework/system/Debug/Toolbar.php(96): CodeIgniter\Debug\Toolbar\Collectors\Database->__construct()
#5 /php_app/vendor/codeigniter4/framework/system/Config/Services.php(856): CodeIgniter\Debug\Toolbar->__construct(Object(Config\Toolbar))
#6 /php_app/vendor/codeigniter4/framework/system/Config/BaseService.php(123): CodeIgniter\Config\Services::toolbar(Object(Config\Toolbar), false)
#7 /php_app/vendor/codeigniter4/framework/system/Config/Services.php(848): CodeIgniter\Config\BaseService::getSharedInstance('toolbar', NULL)
#8 /php_app/app/Config/Events.php(50): CodeIgniter\Config\Services::toolbar()
#9 [internal function]: CodeIgniter\Events\Events::Config\{closure}()
#10 /php_app/vendor/codeigniter4/framework/system/Events/Events.php(188): call_user_func(Object(Closure))
#11 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(293): CodeIgniter\Events\Events::trigger('pre_system')
#12 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-07-21 03:27:02 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 03:28:06 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 03:30:13 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-21 03:33:51 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin8@gmai...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin8@gmai...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
