CRITICAL - 2022-07-23 02:13:20 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 02:16:06 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 02:16:12 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 02:16:21 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 02:16:41 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 02:17:05 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 02:17:20 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-23 02:17:44 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 02:23:55 --> Class '\CodeIgniter\Database\pdo\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 02:24:23 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-23 02:41:21 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(240): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#4 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#5 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#6 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#9 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2022-07-23 02:42:14 --> Class '\CodeIgniter\Database\PDO_MySQL\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 02:43:04 --> Class '\CodeIgniter\Database\PDO_MySQL\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 02:48:19 --> syntax error, unexpected '$custom' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
#0 /php_app/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('/php_app/app/Co...')
#1 /php_app/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Database')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Database')
#3 /php_app/vendor/codeigniter4/framework/system/Debug/Toolbar/Collectors/Database.php(100): spl_autoload_call('Config\\Database')
#4 /php_app/vendor/codeigniter4/framework/system/Debug/Toolbar.php(96): CodeIgniter\Debug\Toolbar\Collectors\Database->__construct()
#5 /php_app/vendor/codeigniter4/framework/system/Config/Services.php(856): CodeIgniter\Debug\Toolbar->__construct(Object(Config\Toolbar))
#6 /php_app/vendor/codeigniter4/framework/system/Config/BaseService.php(123): CodeIgniter\Config\Services::toolbar(Object(Config\Toolbar), false)
#7 /php_app/vendor/codeigniter4/framework/system/Config/Services.php(848): CodeIgniter\Config\BaseService::getSharedInstance('toolbar', NULL)
#8 /php_app/app/Config/Events.php(50): CodeIgniter\Config\Services::toolbar()
#9 [internal function]: CodeIgniter\Events\Events::Config\{closure}()
#10 /php_app/vendor/codeigniter4/framework/system/Events/Events.php(188): call_user_func(Object(Closure))
#11 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(293): CodeIgniter\Events\Events::trigger('pre_system')
#12 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-07-23 02:49:23 --> syntax error, unexpected '$db' (T_VARIABLE), expecting function (T_FUNCTION) or const (T_CONST)
#0 /php_app/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(296): CodeIgniter\Autoloader\Autoloader->requireFile('/php_app/app/Co...')
#1 /php_app/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(258): CodeIgniter\Autoloader\Autoloader->loadInNamespace('Config\\Database')
#2 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('Config\\Database')
#3 /php_app/vendor/codeigniter4/framework/system/Debug/Toolbar/Collectors/Database.php(100): spl_autoload_call('Config\\Database')
#4 /php_app/vendor/codeigniter4/framework/system/Debug/Toolbar.php(96): CodeIgniter\Debug\Toolbar\Collectors\Database->__construct()
#5 /php_app/vendor/codeigniter4/framework/system/Config/Services.php(856): CodeIgniter\Debug\Toolbar->__construct(Object(Config\Toolbar))
#6 /php_app/vendor/codeigniter4/framework/system/Config/BaseService.php(123): CodeIgniter\Config\Services::toolbar(Object(Config\Toolbar), false)
#7 /php_app/vendor/codeigniter4/framework/system/Config/Services.php(848): CodeIgniter\Config\BaseService::getSharedInstance('toolbar', NULL)
#8 /php_app/app/Config/Events.php(50): CodeIgniter\Config\Services::toolbar()
#9 [internal function]: CodeIgniter\Events\Events::Config\{closure}()
#10 /php_app/vendor/codeigniter4/framework/system/Events/Events.php(188): call_user_func(Object(Closure))
#11 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(293): CodeIgniter\Events\Events::trigger('pre_system')
#12 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-07-23 02:49:40 --> Constant expression contains invalid operations
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-07-23 02:51:14 --> Constant expression contains invalid operations
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-07-23 02:51:39 --> Constant expression contains invalid operations
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-07-23 02:51:58 --> Constant expression contains invalid operations
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-07-23 02:52:31 --> Constant expression contains invalid operations
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-07-23 02:54:13 --> Class '\CodeIgniter\Database\PDO_MySQL\Connection' not found
#0 /php_app/vendor/codeigniter4/framework/system/Database/Config.php(115): CodeIgniter\Database\Database->load(Array, 'default')
#1 /php_app/vendor/codeigniter4/framework/system/Validation/Rules.php(225): CodeIgniter\Database\Config::connect('default')
#2 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(325): CodeIgniter\Validation\Rules->is_unique('supawarin88@gma...', 'user_email', Array, NULL)
#3 /php_app/vendor/codeigniter4/framework/system/Validation/Validation.php(189): CodeIgniter\Validation\Validation->processRules('email', 'email', 'supawarin88@gma...', Array, Array)
#4 /php_app/vendor/codeigniter4/framework/system/Controller.php(219): CodeIgniter\Validation\Validation->run()
#5 /php_app/app/Controllers/Register.php(26): CodeIgniter\Controller->validate(Array)
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Register->save()
#7 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Register))
#8 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2022-07-23 05:04:52 --> syntax error, unexpected end of file, expecting '('
#0 /php_app/app/Controllers/Register.php(13): helper(Array)
#1 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(890): App\Controllers\Register->__construct()
#2 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(399): CodeIgniter\CodeIgniter->createController()
#3 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-07-23 05:40:10 --> Unable to connect to the database.
#0 /php_app/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->initialize()
#1 /php_app/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1860): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 /php_app/vendor/codeigniter4/framework/system/Model.php(506): CodeIgniter\Database\BaseBuilder->get()
#3 /php_app/app/Controllers/Login.php(19): CodeIgniter\Model->first()
#4 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(918): App\Controllers\Login->auth()
#5 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(404): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#6 /php_app/vendor/codeigniter4/framework/system/CodeIgniter.php(312): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /php_app/public/index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
